apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # Or "alb" if using AWS Load Balancer Controller
spec:
  type: LoadBalancer
  selector:
    app: flaskapp
  ports:
    - port: 80
      targetPort: 8080

